### ISSUE TITLE
No HDMI output

### ISSUE THREAD

**Issue by tomasz-drgas** [reemo3dp/mellowfly-geminipi-armbian#4]
I hooked up a known working screen (Waveshare 4.3inch, works fine with FlyOS without any configuration), but there's no output when I boot this version of Armbian. Do I need to do anything specific to enable HDMI out?

**Comment by reemo3dp** [comment]
Hi @tomasz-drgas , I haven't tried using a HDMI screen with these patches yet. I remember tinkering with that very early on, but I wasn't too confident in the device tree.

I can't promise I will get to this in due time, so if you require HDMI, I suggest you stick with the flyOS images for the time being.

**Comment by tomasz-drgas** [comment]
HDMI support would be a nice thing to have, for me it was always the least painful thing to use for setting up KlipperScreen with touch support. What kind of displays are supported? I own a Mellow Fly TFT v1 3.5" display, but I'm missing the FPC cable to connect it to Gemini v3

**Comment by reemo3dp** [comment]
I don't provide support at all, I don't even have the gemini working in a printer right now. 

The device tree overlays used to enable HDMI and the Mellow SPI screens should work for these images too, but I neither have time nor hardware to get it working.
